version: '3.8'

services:
  server:
    build: 
      context: ./server
      dockerfile: Dockerfile
    command: npx nodemon -L app.js
    ports:
      - '8100:8100'
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - MONGO_URI=mongodb://mongo:27017/hanguru
      - GCS_SERVICE_ACCOUNT=/usr/src/app/gcs-service-account.json
      - SPEECH_TO_TEXT_SERVICE_ACCOUNT=/usr/src/app/speech-to-text-service-account.json
      - GOOGLE_APPLICATION_CREDENTIALS=/usr/src/app/text-to-speech-service-account.json
      - GCS_BUCKET_NAME=hanguru-audio-bucket
    env_file: 
      - ./server/.env
    depends_on:
      - mongo
      - cloud_sql_proxy

  client:
    build: 
      context: ./client
      dockerfile: Dockerfile
    ports:
      - '3000:80'
    depends_on:
      - server

  mongo:
    image: mongo
    ports:
      - '27017:27017'
    restart: unless-stopped

  cloud_sql_proxy:
    image: gcr.io/cloudsql-docker/gce-proxy:1.24.0
    command: /cloud_sql_proxy -instances=hanguru-405413:us-east4:hanguru-profile-pics-db=tcp:0.0.0.0:3306 -credential_file=/config
    volumes:
      - /server/cloud-proxy-service-account.json:/config
    restart: unless-stopped
