version: '3'
services:
  app:
    container_name: node_app
    restart: always
    build: ./
    ports:
      - "8080:8080"
    environment:
      - MONGO_URI=mongodb://mongo:27017/hanguru
      - PORT=8080
    depends_on:
      - mongo
  mongo:
    container_name: mongo_db
    image: mongo
    ports:
      - "27017:27017"
