version: '3.8'

services:
  server:
    build: 
      context: ./server
      dockerfile: Dockerfile
    command: npx nodemon -L app.js
    networks:
      - hanguru_network
    ports:
      - '8100:8100'
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
    env_file: 
      - ./server/.env

  client:
    build: 
      context: ./client
      dockerfile: Dockerfile
    networks:
      - hanguru_network
    ports:
      - '3000:80'

networks:
  hanguru_network:
    driver: bridge
