name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build Client Docker Image
      run: docker build -t node:18-bullseye-slim:latest ./client

    - name: Build Server Docker Image
      run: docker build -t node:18-bullseye-slim:latest ./server

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-test
    if: github.ref == 'refs/heads/main'
    steps:
    - uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Push Client Image to Docker Hub
      run: docker push node:18-bullseye-slime:latest

    - name: Push Server Image to Docker Hub
      run: docker push node:18-bullseye-slim:latest

