name: CI/CD Pipeline for Production Branch

on:
  push:
    branches: [ production ]
  pull_request:
    branches: [ production ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build Client Docker Image
      run: docker build -t yourapp-client:staging ./client

    - name: Build Server Docker Image
      run: docker build -t yourapp-server:staging ./server

  deploy-to-staging:
    runs-on: ubuntu-latest
    needs: build-and-test
    if: github.ref == 'refs/heads/production'
    steps:
    - uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Push Client Image to Docker Hub
      run: docker push yourapp-client:staging

    - name: Push Server Image to Docker Hub
      run: docker push yourapp-server:staging

